In [2]:
import numpy as np

In [3]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [4]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a.resize(12, 1)
print(a)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [10]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
np.reshape(a, (-1, 6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
np.reshape(a, (-1, 2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [15]:
a.ndim

2

In [17]:
a = np.random.randn(3, 4)
print(a)

[[ 0.13305443 -0.12335704 -2.51509873  0.13462247]
 [-0.08854016  2.00416467  0.11957774 -0.31568913]
 [-1.18779654 -0.31579219  1.64230803 -1.15251848]]


In [18]:
b = a.flatten()
print(b)

[ 0.13305443 -0.12335704 -2.51509873  0.13462247 -0.08854016  2.00416467
  0.11957774 -0.31568913 -1.18779654 -0.31579219  1.64230803 -1.15251848]


In [19]:
a.size == b.size

True

In [20]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [21]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


Разницы нет

In [25]:
np.array_equal(a, b)

True

In [26]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print('Массив a ', a, sep='\n')
print('Массив b ', b, sep='\n')

Массив a 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Массив b 
[[1. 1.]
 [1. 1.]]


In [27]:
v = np.concatenate((a, b), axis = 0)
print(v)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [28]:
v.size

10

In [29]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [32]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


При умножении матриц число строк итоговой матрицы (B) равно число строк первой матрицы (A), а число столбцов - второй матрицы (At).

In [33]:
B.size

16

Вычислить обратную матрицу для B невозможно, т.к. определитель матрицы B равен 0.

In [34]:
np.linalg.det(B)

0.0

In [38]:
np.random.seed(42)

In [39]:
a = np.arange(0, 16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [40]:
np.sqrt(a.size)

4.0

In [41]:
C = a.reshape((4, 4))
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [42]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [43]:
C.shape == B.shape

True

In [49]:
D = 10 * C + B
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [51]:
np.linalg.det(D)

0.0

Не могу понять, в чем ошибка